-- Combined migration script (up to 095_order_ncs_sequentially_by_constatations.sql)
-- This script sequentially includes all migration files from the initial setup through 095.
-- It can be executed with psql (or supabase db reset) to bring a fresh database
-- to the schema state of commit 3ece4da4f144abb6fe7cd45ada0ae7883265482c.

BEGIN;
\i ./000_setup_completo.sql
\i ./001_initial_schema.sql
\i ./002_fix_ativo_columns.sql
\i ./003_seed_municipios_ms.sql
\i ./004_update_itens_checklist_schema.sql
\i ./005_fix_municipios_schema.sql
\i ./006_force_schema_refresh.sql
\i ./008_fix_rls_policies_v2.sql
\i ./010_create_admin_user.sql
\i ./011_create_admin_user_safe.sql
\i ./012_update_user_approval_flow.sql
\i ./013_fix_auth_trigger_robustness.sql
\i ./014_emergency_fix_auth.sql
\i ./015_isolate_login_error.sql
\i ./016_fix_auth_properly.sql
\i ./017_switch_to_client_side_profile.sql
\i ./019_reset_admin_clean.sql
\i ./020_fix_profile_insert_policy.sql
\i ./021_confirm_emails.sql
\i ./022_bypass_rate_limit.sql
\i ./023_promote_jsilva_admin.sql
\i ./024_allow_admin_delete_profile.sql
\i ./025_manual_create_user.sql
\i ./027_auto_confirm_email.sql
\i ./028_seed_prestadores.sql
\i ./029_update_prestadores_schema.sql
\i ./030_update_prestadores_endereco.sql
\i ./031_add_unidade_coords.sql
\i ./032_check_columns.sql
\i ./033_fix_unidades_rls.sql
\i ./034_add_endereco_unidade.sql
\i ./035_add_data_vistoria.sql
\i ./036_final_unidades_fix.sql
\i ./037_check_itens.sql
\i ./038_fix_respostas_schema.sql
\i ./039_fix_respostas_checklist_schema.sql
\i ./040_test_insert_resposta.sql
\i ./041_fix_resposta_type.sql
\i ./042_seed_test_data.sql
\i ./043_add_item_checklist_id.sql
\i ./044_create_storage_bucket.sql
\i ./045_fix_recomendacoes_schema.sql
\i ./046_fix_constatacoes_manuais_schema.sql
\i ./047_match_constatacoes_manuais_schema.sql
\i ./048_fix_ordem_type.sql
\i ./051_update_rpc_gerar_ncs_unidade.sql
\i ./052_create_rpc_finalizar_fiscalizacao.sql
\i ./053_add_evidencias_respostas_determinacao.sql
\i ./054_create_evidencias_bucket.sql
\i ./055_update_roles_schema.sql
\i ./056_admin_delete_auth_user.sql
\i ./057_create_relatorios_bucket.sql
\i ./058_create_relatorios_jobs.sql
\i ./059_add_termos_notificacao_assinatura_prestador.sql
\i ./060_fix_relatorios_delete_policies.sql
\i ./061_force_open_rls_for_sync.sql
\i ./062_fluxo_portal_manual_am_remessas_ai.sql
\i ./063_fix_fiscalizacoes_created_by_default.sql
\i ./064_lockdown_relatorios_access.sql
\i ./065_add_rpc_reabrir_fiscalizacao.sql
\i ./066_fix_manual_ncs_and_photo_sync.sql
\i ./067_dedupe_respostas_checklist.sql
\i ./068_backfill_item_checklist_id_respostas.sql
\i ./069_fix_gerar_ncs_unidade_dedupe_respostas.sql
\i ./070_fix_finalizar_fiscalizacao_safe_columns.sql
\i ./071_numero_termo_por_ordem_criacao.sql
\i ./072_add_descricao_nc_updated_at_constatacoes_manuais.sql
\i ./073_fix_constatacoes_manuais_ordem_bigint.sql
\i ./074_fix_manual_descricao_nc_after_renumber.sql
\i ./075_dedupe_and_unique_unidade_por_fiscalizacao_codigo.sql
\i ./076_add_updated_at_respostas_checklist.sql
\i ./077_repair_unidade_codigo_duplicates_then_unique.sql
\i ./078_fix_nc_descricao_null_guard.sql
\i ./079_recomendacoes_schema_dedupe_unique.sql
\i ./080_update_gerar_ncs_unidade_recomendacoes_override.sql
\i ./081_fix_gerar_ncs_unidade_recomendacoes_no_on_conflict.sql
\i ./082_add_determinacoes_origem_updated_at.sql
\i ./083_termos_notificacao_tipo_relatorio_unique.sql
\i ./084_update_determinacoes_texto_padrao_sanar_nc.sql
\i ./085_secure_rls_policies.sql
\i ./086_enforce_profiles_security.sql
\i ./087_secure_checklists_and_remessas.sql
\i ./088_secure_remaining_tables.sql
\i ./089_performance_indexes.sql
\i ./090_admin_update_role_rpc.sql
\i ./091_fix_respostas_checklist_unique_index.sql
\i ./092_fix_finalizar_e_ncs_robustness.sql
\i ./093_optimize_ncs_performance.sql
\i ./094_fix_gerar_ncs_parameter_ambiguity.sql
\i ./095_order_ncs_sequentially_by_constatations.sql
COMMIT;
